import os
import shutil
import json
import logging

logger = logging.getLogger("generator")

class NextJsGenerator:
    def __init__(self, output_dir: str):
        # output_dir points to backend/projects/{project_id}
        self.output_dir = output_dir

    def generate_project(self, project_name: str, scraped_data: dict, text_blocks: list) -> str:
        """
        Generates a runnable Next.js 15 project structure.
        """
        app_path = os.path.join(self.output_dir, project_name)
        os.makedirs(app_path, exist_ok=True)
        
        logger.info(f"Generating Next.js project at: {app_path}")
        
        # 1. Create directories
        public_dir = os.path.join(app_path, "public")
        app_routes_dir = os.path.join(app_path, "app")
        os.makedirs(public_dir, exist_ok=True)
        os.makedirs(app_routes_dir, exist_ok=True)
        
        # 2. Copy scraped assets to Next.js public directory
        scraped_assets_dir = os.path.join(self.output_dir, "scraped", "assets")
        if os.path.exists(scraped_assets_dir):
            dest_assets_dir = os.path.join(public_dir, "assets")
            # Clear if already exists
            if os.path.exists(dest_assets_dir):
                shutil.rmtree(dest_assets_dir)
            shutil.copytree(scraped_assets_dir, dest_assets_dir)
            logger.info("Copied scraped assets to public/assets")
            
        # 3. Copy scraped index.html to project root
        scraped_html_path = scraped_data["html_path"]
        dest_html_path = os.path.join(app_path, "index.html")
        if os.path.exists(scraped_html_path):
            shutil.copy2(scraped_html_path, dest_html_path)
            logger.info("Copied index.html to Next.js project root")
            
        # 4. Write content.json (key-value text map)
        content_json_path = os.path.join(app_path, "content.json")
        content_map = {tb["key"]: tb["current_value"] for tb in text_blocks}
        with open(content_json_path, "w", encoding="utf-8") as f:
            json.dump(content_map, f, indent=2)
            
        # 5. Write text_blocks_meta.json (selector mapping)
        meta_json_path = os.path.join(app_path, "text_blocks_meta.json")
        with open(meta_json_path, "w", encoding="utf-8") as f:
            json.dump(text_blocks, f, indent=2)
            
        # 6. Create package.json
        package_json_path = os.path.join(app_path, "package.json")
        package_json_content = {
            "name": "cloned-website-ai",
            "version": "0.1.0",
            "private": True,
            "scripts": {
                "dev": "next dev",
                "build": "next build",
                "start": "next start"
            },
            "dependencies": {
                "react": "^18.3.1",
                "react-dom": "^18.3.1",
                "next": "^14.2.3",
                "cheerio": "^1.0.0-rc.12"
            }
        }
        with open(package_json_path, "w", encoding="utf-8") as f:
            json.dump(package_json_content, f, indent=2)
            
        # 7. Create app/layout.tsx
        layout_path = os.path.join(app_routes_dir, "layout.tsx")
        layout_content = """import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cloned Website Preview",
  description: "Generated by Website Cloner AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>{children}</body>
    </html>
  );
}
"""
        with open(layout_path, "w", encoding="utf-8") as f:
            f.write(layout_content)
            
        # 8. Create app/page.tsx (Server Component doing dynamic selector replacement)
        page_path = os.path.join(app_routes_dir, "page.tsx")
        page_content = """import fs from 'fs';
import path from 'path';
import cheerio from 'cheerio';

export const dynamic = 'force-dynamic';

export default async function Page() {
  const htmlPath = path.join(process.cwd(), 'index.html');
  const contentPath = path.join(process.cwd(), 'content.json');
  const metaPath = path.join(process.cwd(), 'text_blocks_meta.json');
  
  if (!fs.existsSync(htmlPath)) {
    return <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}><h1>No Cloned Page Found</h1></div>;
  }
  
  let html = fs.readFileSync(htmlPath, 'utf8');
  
  // Read and replace values
  if (fs.existsSync(contentPath) && fs.existsSync(metaPath)) {
    try {
      const content = JSON.parse(fs.readFileSync(contentPath, 'utf8'));
      const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
      
      const $ = cheerio.load(html);
      
      for (const block of meta) {
        const value = content[block.key];
        if (value !== undefined) {
          // Replace text element content
          const el = $(block.selector);
          if (el.length > 0) {
            el.text(value);
          }
        }
      }
      html = $.html();
    } catch (e) {
      console.error("Failed to parse edit metadata or replace content:", e);
    }
  }
  
  return (
    <div dangerouslySetInnerHTML={{ __html: html }} />
  );
}
"""
        with open(page_path, "w", encoding="utf-8") as f:
            f.write(page_content)
            
        # 9. Create an empty next.config.js if needed (for custom configurations)
        next_config_path = os.path.join(app_path, "next.config.mjs")
        next_config_content = """/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  // Allow loading local resource URLs
  images: {
    unoptimized: true
  }
};

export default nextConfig;
"""
        with open(next_config_path, "w", encoding="utf-8") as f:
            f.write(next_config_content)
            
        logger.info(f"Next.js project generation complete for {project_name}")
        return app_path
